# Site settings
title: Lucas Dasso Â· <span class="fw-lighter">Digital Corner</span>
baseurl: ""
url: "https://me.c238.com.ar"
google_analytics: G-VQK8L4H9C2

# Author
author:
  name: Lucas Dasso
  desc: "Laziness, impatience, and hubris."
  email: dassolucas@gmail.com
  selfie: assets/img/profile.png

# Social (only keep the ones you actually use)
social:
  email: true
  github: lukas238
  instagram: dassolucas
  linkedin: https://www.linkedin.com/in/lucasdasso
  twitter: lucasdasso
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Encoding (para manejar correctamente tildes y caracteres especiales)
encoding: utf-8

# Assets
sass:
  sass_dir: _sass
  style: compressed


# Backgrounds gallery
bg_images_url: "/assets/backgrounds/"
bg_thumbs_url: "/assets/backgrounds/_thumbs/"

# Plugins
plugins:
  - jekyll-paginate

# Pages
include:
  - _pages
  - _thumbs

# Excludes
exclude:
  - vendor
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "README.md"
  - "screenshot.png"
  - "package.json"
  - "package-lock.json"
  - "node_modules"
  - "scritps/*"
